const unsigned char gameover_nam[81];
const unsigned char level1_nam[305];
const unsigned char level2_nam[459];
const unsigned char level3_nam[540];
const unsigned char level4_nam[640];
const unsigned char level5_nam[851];
const unsigned char level_nam[52];
const unsigned char title_nam[380];
const unsigned char welldone_nam[106];
